name: Docker Image CI

on:
  push:
    branches: [ feature/adding_jenkins_docker ]
  pull_request:
    branches: [ feature/adding_jenkins_docker ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository on branch jenkin docker
        uses: actions/checkout@v3
        with:
          ref: feature/adding_jenkins_docker
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

