name: Docker Image CI

on:
  push:
    branches: [ feature/adding_jenkins_docker ]
  pull_request:
    branches: [ feature/adding_jenkins_docker ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository on branch jenkin docker
        uses: actions/checkout@v3
        with:
          ref: feature/adding_jenkins_docker
#       - name: print out secret variables
#         run: echo ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_TOKEN }} | sed 's/./& /g'
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./Jenkins_Docker
          file: ./Jenkins_Docker/Dockerfile
          push: true
          tags: blackkoala/koala-jenkins-docker:latest

      

